---
title: "COVID in Saskatchewan"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source_code: "https://github.com/SaskOpenData/covid19-sask"
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(dygraphs)
library(highcharter)
library(xts)
library(zoo)
source('../utils.R')

indata <- readr::read_csv('../data/cases-sk.csv')
indata$Active <- indata$Cases - indata$Recovered - indata$Deaths
cases <- xts(indata$Cases, order.by=indata$Date)
colnames(cases) <- c('Cases')
```

Summary
======================================================================

Row 
-----------------------------------------------------------------------

### Active cases
```{r}
casesCurr <- indata[nrow(indata), "Active"]
valueBox(casesCurr, 
         icon = "fa-stethoscope",
         color = ifelse(casesCurr > 5, "warning", ifelse(casesCurr > 100, "danger", "primary"))
)
```

### Daily growth
```{r}
dailyGrowth <- indata[nrow(indata), 'Active']/indata[nrow(indata)-1, 'Active']-1
valueBox(round(dailyGrowth*100,0), 
         icon = "fa-percent",
         color = ifelse(dailyGrowth > 0.3, "danger", "warning"))
```

### Deaths
```{r}
deathsCurr <- indata[nrow(indata), "Deaths"]
valueBox(deathsCurr, 
         icon = "fa-skull",
         color = ifelse(deathsCurr == 0, "success", "danger"))
```

### Recovered
```{r}
recoverCurr <- indata[nrow(indata), "Recovered"]
valueBox(recoverCurr, 
         icon = "fa-syringe",
         color = ifelse(recoverCurr > 0, "primary", "success"))
```


Row
-----------------------------------------------------------------------

### Official cases chart

```{r}
highchart() %>%
  hc_title(text = "Official COVID-19 Cases in Saskatchewan",
           style = list(fontSize = "15px")) %>% 
  hc_chart(type = "area", polar=FALSE) %>% 
  hc_xAxis(categories = indata$Date) %>%
  hc_plotOptions(
    area = list(
      stacking = "normal"
    )
  ) %>%
  hc_add_series(indata$Recovered, name= "Recovered") %>%
  hc_add_series(indata$Active, name = "Active cases") %>%
  hc_add_series(indata$Deaths, name="Deaths")

```




Policy tools
======================================================================

Row 
-----------------------------------------------------------------------

### Detection rate
```{r}
detectionRate <- detRate(indata$Cases, indata$Deaths)
valueBox(round(detectionRate*100, 2), 
         icon = "fa-percent",
         color = ifelse(detectionRate > 50, "success", ifelse(detectionRate > 25, "primary", "danger"))
)
```

### Doubling rate (days)
```{r}
doubRate <- round(doubTime(indata$Active, 1:length(indata$Active)), 1)
valueBox(doubRate, 
         icon = "fa-stethoscope",
         color = ifelse(doubRate > 5, "success", ifelse(doubRate < 2.5, "danger", "warning"))
)
```

### Forecasted cases (10-day)
```{r}
projectedCases <- floor(as.data.frame(projSimple(indata$Active, 1:length(indata$Active))$y)$fit)
fcastCases <- projectedCases[length(projectedCases)]
valueBox(fcastCases, 
         icon = "fa-stethoscope",
         color = "danger"
)
```

### Inferred actual current cases
```{r}
indata$inferredCases <- floor(indata$Active/detectionRate)
inferredCases <- indata$inferredCases[length(indata$Active)]
valueBox(inferredCases, 
         icon = "fa-stethoscope",
         color = "danger"
)
```


### Positive testing rate
```{r}
indata$pos_test_rate <- indata$New/indata$Tests
pos_rate <- round(100*tail(indata$pos_test_rate, 1), 2)
valueBox(pos_rate, 
         icon = "fa-percent",
         color = "danger"
)
```

Row
-----------------------------------------------------------------------

### Growth rate of confirmed cases

```{r}
indata$Growth <- c(NA, 100*diff(indata$Active)/indata$Active[1:(nrow(indata)-1)])
# names(gr) <- 'Growth'
highchart() %>%
  hc_title(text = "COVID-19 Growth rate",
           style = list(fontSize = "15px")) %>% 
  hc_chart(type = "line") %>%
  hc_xAxis(categories = indata$Date) %>%
  hc_add_series(indata$Growth, name = "Growth rate")
```





